/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEndGUI;

import FrontEndGUI.*;
import BackEndCode.Bootstrap;
import BackEndCode.CodeSet;
import BackEndCode.MySQLQueries;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author Sai
 */
public class EditCustAcc extends javax.swing.JFrame {

    /**
     * Creates new form NewCAcc
     */
    private MySQLQueries SQuery = null;

    private CodeSet codeset = null;

    private static Connection conn = null;

    private static JFrame frame;

    private static ArrayList<String> ls, lp;

    private static String staff;

    int mouseX;
    int mouseY;

    public EditCustAcc(Connection conn, JFrame frame, ArrayList<String> ls, String staff) {
        this.conn = conn;
        this.frame = frame;
        this.ls = ls;
        this.staff = staff;
        this.setUndecorated(true);
        initComponents();
        this.setFocusable(true);
        SQuery = new MySQLQueries(conn);
        populateCountryList();
        dt.setVisible(false);
        per.setVisible(false);
        pers.setVisible(false);
        initiateData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lName = new javax.swing.JTextField();
        postcode = new javax.swing.JTextField();
        ad2 = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        ad1 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        country = new javax.swing.JComboBox<>();
        county = new javax.swing.JTextField();
        error = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        type = new javax.swing.JComboBox<>();
        dtype = new javax.swing.JComboBox<>();
        dt = new javax.swing.JComboBox<>();
        per = new javax.swing.JTextField();
        pers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(59, 63, 66));
        jPanel2.setForeground(new java.awt.Color(59, 63, 66));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(171, 172, 173));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 172, 173));
        jLabel1.setText("Edit Customer Account");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 280, -1));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -10, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 60));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lName.setText("Last Name");
        jPanel1.add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 280, -1));

        postcode.setText("Postcode");
        jPanel1.add(postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 120, -1));

        ad2.setText("Address 2 (optional)");
        ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad2ActionPerformed(evt);
            }
        });
        jPanel1.add(ad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 280, -1));

        fName.setText("First Name");
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        jPanel1.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 280, -1));

        phone.setText("Contact Number");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 280, -1));

        city.setText("Town/City");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, -1));

        ad1.setText("Address 1");
        jPanel1.add(ad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, -1));

        email.setText("Email Address");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 360, 120, -1));

        country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Country", "Item 2", "Item 3", "Item 4" }));
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 150, -1));

        county.setText("County (Optional)");
        jPanel1.add(county, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 150, -1));

        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 590, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 70, -1));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Organisation" }));
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, -1));

        dtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Valued" }));
        dtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtypeActionPerformed(evt);
            }
        });
        jPanel1.add(dtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 130, -1));

        dt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flexible", "Fixed", "Variable" }));
        dt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtActionPerformed(evt);
            }
        });
        jPanel1.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 120, -1));

        per.setText("Discount %");
        per.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perKeyTyped(evt);
            }
        });
        jPanel1.add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 130, -1));

        pers.setBackground(new java.awt.Color(59, 63, 66));
        pers.setFont(pers.getFont().deriveFont(pers.getFont().getStyle() | java.awt.Font.BOLD, pers.getFont().getSize()+2));
        pers.setForeground(new java.awt.Color(59, 63, 66));
        pers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pers.setText("%");
        pers.setAutoscrolls(true);
        pers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 670, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        error.setText("");
        if (type.getSelectedItem().toString().equals("Individual")) {
            if (lName.getText().equals("Lastname") || lName.getText().equals("")) {
                error.setText("Please fill all the Last Name");
            }
        } else if (type.getSelectedItem().toString().equals("Organisation")) {
            if (lName.getText().equals("Lastname") || lName.getText().equals("")) {
                lName.setText(null);
            }
        }
        if ((fName.getText().equals("First Name") || ad1.getText().equals("Address 1") || city.getText().equals("Town/City") || postcode.getText().equals("Postcode") || email.getText().equals("Email Address") || phone.getText().equals("Contact Number"))
                || (fName.getText().equals("") || ad1.getText().equals("") || city.getText().equals("") || postcode.getText().equals("") || email.getText().equals("") || phone.getText().equals(""))) {
            error.setText("Please fill all the section");
        } else if (!(phone.getText().matches("\\d+")) || (fName.getText().matches(".*\\d+.*")) || (lName.getText().matches(".*\\d+.*")) || !(codeset.isValidEmailAddress(email.getText()))) {
            error.setText("Please enter valid input");
        } else if (dt.getSelectedIndex() == 1 && (per.getText() == null || per.getText().equals("Discount %") || per.getText().isEmpty())) {
            error.setText("Please enter valid discount percentage");
        } else {
            if(dtype.getSelectedIndex()==0){
                dt.addItem("Null");
                dt.setSelectedItem("Null");
                per.setText("0.00");
            }
            if(!(dt.getSelectedIndex()==1)){
                per.setText("0.00");
            }
            if (ad2.getText().equals("Address 2 (optional)")) {
                ad2.setText(null);
            }
            if (county.getText().equals("County (Optional)")) {
                county.setText(null);
            }
            if (SQuery.editCust(finaliseData())) {
                if (type.getSelectedItem().toString().equals("Individual")) {
                    new ICustomerAccount(conn, lp.get(10), frame, staff).setVisible(true);
                } else if (type.getSelectedItem().toString().equals("Organisation")) {
                    new OCustomerAccount(conn, lp.get(10), frame, staff).setVisible(true);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad2ActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        if (type.getSelectedItem().toString().equals("Individual")) {
            new ICustomerAccount(conn, ls.get(10), frame, staff).setVisible(true);
        } else if (type.getSelectedItem().toString().equals("Organisation")) {
            new OCustomerAccount(conn, ls.get(10), frame, staff).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        initiateData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtActionPerformed
        if (dt.getSelectedIndex() == 1) {
            per.setVisible(true);
            pers.setVisible(true);
        } else {
            per.setVisible(false);
            per.setText("0.00");
            pers.setVisible(false);
        }
    }//GEN-LAST:event_dtActionPerformed

    private void dtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtypeActionPerformed
        if (dtype.getSelectedIndex() == 1) {
            dt.setVisible(true);
        } else {
            dt.setVisible(false);
            dt.setSelectedIndex(0);
        }
    }//GEN-LAST:event_dtypeActionPerformed

    private void perKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| c == '.')){
            evt.consume();
        }
    }//GEN-LAST:event_perKeyTyped

    public void populateCountryList() {
        codeset = new CodeSet();
        DefaultComboBoxModel dm = new DefaultComboBoxModel(codeset.getAllCountries());
        country.setModel(dm);
        country.setSelectedIndex(77);
    }

    private void initiateData() {
        fName.setText(ls.get(1));
        lName.setText(ls.get(2));
        ad1.setText(ls.get(3));
        ad2.setText(ls.get(4));
        city.setText(ls.get(5));
        county.setText(ls.get(6));
        postcode.setText(ls.get(7));
        country.setSelectedItem(ls.get(8));
        type.setSelectedItem(ls.get(9));
        email.setText(ls.get(10));
        phone.setText(ls.get(11));
        dtype.setSelectedItem(ls.get(12));
        if(dtype.getSelectedIndex()==1){
            dt.setVisible(true);
            if(dt.getSelectedIndex()==1){
                per.setVisible(true);
                pers.setVisible(true);
            }
        }
        dt.setSelectedItem(ls.get(13));
        per.setText(ls.get(14));
    }

    private ArrayList<String> finaliseData() {
        lp = new ArrayList<>();
        lp.add(ls.get(0));
        lp.add(fName.getText());
        lp.add(lName.getText());
        lp.add(ad1.getText());
        lp.add(ad2.getText());
        lp.add(city.getText());
        lp.add(county.getText());
        lp.add(postcode.getText());
        lp.add(country.getSelectedItem().toString());
        lp.add(type.getSelectedItem().toString());
        lp.add(email.getText());
        lp.add(phone.getText());
        lp.add(dtype.getSelectedItem().toString());
        lp.add(dt.getSelectedItem().toString());
        lp.add(per.getText());
        return lp;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustAcc(conn, new JFrame(), new ArrayList<>(), new String()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad1;
    private javax.swing.JTextField ad2;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> country;
    private javax.swing.JTextField county;
    private javax.swing.JComboBox<String> dt;
    private javax.swing.JComboBox<String> dtype;
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField per;
    private javax.swing.JLabel pers;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField postcode;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
