/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEndGUI;

import BackEndCode.CodeSet;
import BackEndCode.IDgen;
import BackEndCode.MySQLQueries;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Sai
 */
public class OCustomerAccount extends javax.swing.JFrame {

    /**
     * Creates new form staffAccount
     */
    private static Connection conn = null;

    private PreparedStatement pst = null;

    private ResultSet rs = null;

    private CodeSet codeset = null;

    private MySQLQueries SQuery = null;

    private String query;

    private static JFrame frame;

    private static String s, staff;

    private int i;

    private IDgen idg;

    private int cid;
    
    private ArrayList<String> ls;

    int mouseX;
    int mouseY;

    public OCustomerAccount(Connection conn, String s, JFrame frame, String staff) {
        this.s = s;
        this.staff = staff;
        this.frame = frame;
        this.conn = conn;
        this.setUndecorated(true);
        idg = new IDgen();
        initComponents();
        SQuery = new MySQLQueries(conn);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initiateData(s);
        table.setModel(new MySQLQueries(conn).populateCTask(String.valueOf(cid)));
        if (role.getText().equals("Default")) {
            pay.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bevelBorder1 = (javax.swing.border.BevelBorder)javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED);
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exit1 = new javax.swing.JButton();
        del = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        accsus = new javax.swing.JPanel();
        suspend = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addTaskPanel = new javax.swing.JPanel();
        addTask = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        address = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cno = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        fName = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(59, 63, 66));
        jPanel9.setForeground(new java.awt.Color(59, 63, 66));
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel9MouseDragged(evt);
            }
        });
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(171, 172, 173));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 172, 173));
        jLabel2.setText("Customer Profile");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 280, -1));

        exit1.setBackground(new java.awt.Color(255, 0, 0));
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setText("X");
        exit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        jPanel9.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, -10, -1, 40));

        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bin2.png"))); // NOI18N
        del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delMouseClicked(evt);
            }
        });
        jPanel9.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 750, 64));

        pay.setText("Payment");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        jPanel1.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 624, 103, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Job ID", "Task", "Status", "Duration", "Price", "Paid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 376, 700, 230));

        accsus.setBackground(new java.awt.Color(153, 153, 153));
        accsus.setForeground(new java.awt.Color(59, 63, 66));
        accsus.setToolTipText("");
        accsus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suspend.setBackground(new java.awt.Color(255, 255, 255));
        suspend.setFont(suspend.getFont().deriveFont(suspend.getFont().getStyle() | java.awt.Font.BOLD, suspend.getFont().getSize()+2));
        suspend.setForeground(new java.awt.Color(255, 255, 255));
        suspend.setText("Suspend");
        suspend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suspendMouseClicked(evt);
            }
        });
        accsus.add(suspend, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 90, 30));

        jLabel9.setBackground(new java.awt.Color(59, 63, 66));
        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD, jLabel9.getFont().getSize()+2));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Task List ");
        accsus.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, 30));

        addTaskPanel.setBackground(new java.awt.Color(102, 102, 102));
        addTaskPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTask.setBackground(new java.awt.Color(171, 172, 173));
        addTask.setFont(addTask.getFont().deriveFont(addTask.getFont().getStyle() | java.awt.Font.BOLD, addTask.getFont().getSize()+2));
        addTask.setForeground(new java.awt.Color(171, 172, 173));
        addTask.setText("+ Add Job");
        addTask.setToolTipText("");
        addTask.setBorderPainted(false);
        addTask.setContentAreaFilled(false);
        addTask.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });
        addTaskPanel.add(addTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        accsus.add(addTaskPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(accsus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 346, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setForeground(new java.awt.Color(59, 63, 66));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        address.setBackground(new java.awt.Color(59, 63, 66));
        address.setFont(address.getFont().deriveFont(address.getFont().getStyle() | java.awt.Font.BOLD, address.getFont().getSize()+2));
        address.setForeground(new java.awt.Color(59, 63, 66));
        address.setText("Northampton Square, London EC1V 0HB  United Kingdom");
        jPanel4.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 570, 30));

        jPanel16.setBackground(new java.awt.Color(59, 63, 66));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(171, 172, 173));
        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getStyle() | java.awt.Font.BOLD, jLabel21.getFont().getSize()+2));
        jLabel21.setForeground(new java.awt.Color(171, 172, 173));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Address");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel16.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 228, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setForeground(new java.awt.Color(59, 63, 66));
        jPanel6.setToolTipText("");
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBackground(new java.awt.Color(59, 63, 66));
        email.setFont(email.getFont().deriveFont(email.getFont().getStyle() | java.awt.Font.BOLD, email.getFont().getSize()+2));
        email.setForeground(new java.awt.Color(59, 63, 66));
        email.setText("sam.winchaster@bapers.com");
        jPanel6.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 30));

        jPanel17.setBackground(new java.awt.Color(59, 63, 66));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(171, 172, 173));
        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getStyle() | java.awt.Font.BOLD, jLabel22.getFont().getSize()+2));
        jLabel22.setForeground(new java.awt.Color(171, 172, 173));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Email");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 276, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setForeground(new java.awt.Color(59, 63, 66));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        role.setBackground(new java.awt.Color(59, 63, 66));
        role.setFont(role.getFont().deriveFont(role.getFont().getStyle() | java.awt.Font.BOLD, role.getFont().getSize()+2));
        role.setForeground(new java.awt.Color(59, 63, 66));
        role.setText("Office Manager");
        jPanel3.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 210, 30));

        jPanel11.setBackground(new java.awt.Color(59, 63, 66));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(171, 172, 173));
        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+2));
        jLabel5.setForeground(new java.awt.Color(171, 172, 173));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Type ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 132, 350, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(59, 63, 66));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setBackground(new java.awt.Color(59, 63, 66));
        id.setFont(id.getFont().deriveFont(id.getFont().getStyle() | java.awt.Font.BOLD, id.getFont().getSize()+2));
        id.setForeground(new java.awt.Color(59, 63, 66));
        id.setText("223445256");
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 30));

        jPanel12.setBackground(new java.awt.Color(59, 63, 66));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(59, 63, 66));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(171, 172, 173));
        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getStyle() | java.awt.Font.BOLD, jLabel20.getFont().getSize()+2));
        jLabel20.setForeground(new java.awt.Color(171, 172, 173));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ID");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 132, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setForeground(new java.awt.Color(59, 63, 66));
        jPanel7.setToolTipText("");
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cno.setBackground(new java.awt.Color(59, 63, 66));
        cno.setFont(cno.getFont().deriveFont(cno.getFont().getStyle() | java.awt.Font.BOLD, cno.getFont().getSize()+2));
        cno.setForeground(new java.awt.Color(59, 63, 66));
        cno.setText("089438766645");
        jPanel7.add(cno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 210, 30));

        jPanel18.setBackground(new java.awt.Color(59, 63, 66));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(171, 172, 173));
        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getStyle() | java.awt.Font.BOLD, jLabel23.getFont().getSize()+2));
        jLabel23.setForeground(new java.awt.Color(171, 172, 173));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Contact Number");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel18.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel7.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 276, 350, -1));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setForeground(new java.awt.Color(59, 63, 66));
        jPanel8.setToolTipText("");
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fName.setBackground(new java.awt.Color(59, 63, 66));
        fName.setFont(fName.getFont().deriveFont(fName.getFont().getStyle() | java.awt.Font.BOLD, fName.getFont().getSize()+2));
        fName.setForeground(new java.awt.Color(59, 63, 66));
        fName.setText("Sam");
        jPanel8.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 520, 30));

        jPanel14.setBackground(new java.awt.Color(59, 63, 66));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(171, 172, 173));
        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getStyle() | java.awt.Font.BOLD, jLabel19.getFont().getSize()+2));
        jLabel19.setForeground(new java.awt.Color(171, 172, 173));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Organisation Name");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        edit.setBackground(new java.awt.Color(59, 63, 66));
        edit.setFont(edit.getFont().deriveFont(edit.getFont().getStyle() | java.awt.Font.BOLD, edit.getFont().getSize()+2));
        edit.setForeground(new java.awt.Color(59, 63, 66));
        edit.setText("Edit Profile");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 760, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        frame.enable(true);
        this.dispose();
    }//GEN-LAST:event_exit1ActionPerformed

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseDragged
        this.setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_jPanel9MouseDragged

    private void delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delMouseClicked
        this.enable(false);
        new Delete(conn, String.valueOf(cid), false, this, frame).show();
    }//GEN-LAST:event_delMouseClicked

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskActionPerformed

        new CreateJob(conn, id.getText(), cid, false, frame, s, role.getText(), staff).show();
        this.dispose();
    }//GEN-LAST:event_addTaskActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        new Payment(conn, this, frame, cid).show();
        this.dispose();
    }//GEN-LAST:event_payActionPerformed

    private void suspendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspendMouseClicked
        if (staff.equals("Office Manager") || staff.equals("Shift Manager")) {
            if (suspend.getText().equals("Suspended")) {
                new MySQLQueries(conn).setAccountStatus(false, cid);
                this.initiateData(s);
            } else {
                new MySQLQueries(conn).setAccountStatus(true, cid);
                this.initiateData(s);
            }
        }
    }//GEN-LAST:event_suspendMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked

        new EditCustAcc(conn,frame,ls,staff).show();
        this.dispose();
    }//GEN-LAST:event_editMouseClicked

    public void initiateData(String s) {
        ls = new ArrayList<>();
        try {
            query = "select * from customer_account where email=\"" + s + "\"";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            while (rs.next()) {
                cid = rs.getInt("customer_id");
                id.setText(idg.generate(cid, 2));
                role.setText(rs.getString("type"));
                fName.setText(rs.getString("first_name"));
                String add2 = rs.getString("address_2");
                String county = rs.getString("county");
                if (add2 == null || add2.isEmpty()) {
                    add2 = "";
                } else {
                    add2 = add2 + ", ";
                }
                if (county == null || county.isEmpty()) {
                    county = "";
                } else {
                    county = county + ", ";
                }
                address.setText(rs.getString("address_1") + ", " + add2 + rs.getString("town_city") + ", " + county + rs.getString("postcode") + ", " + rs.getString("country"));
                email.setText(rs.getString("email"));
                cno.setText(String.valueOf(rs.getLong("contact_no")));
                if (!rs.getBoolean("suspended")) {
                    accsus.setBackground(Color.GREEN);
                    suspend.setText("Active");
                    addTask.setVisible(true);
                    addTaskPanel.setVisible(true);
                } else {
                    accsus.setBackground(Color.red);
                    suspend.setText("Suspended");
                    addTask.setVisible(false);
                    addTaskPanel.setVisible(false);
                }
                if(staff.equals("Office Manager")||staff.equals("Shift Manager")){
                    del.enable();
                    del.setVisible(true);
                    edit.enable();
                    edit.setVisible(true);
                }else{
                    del.disable();
                    del.setVisible(false);
                    edit.disable();
                    edit.setVisible(false);
                }
                
                ls.add(String.valueOf(rs.getInt("customer_id")));
                ls.add(rs.getString("first_name"));
                ls.add(rs.getString("last_name"));
                ls.add(rs.getString("address_1"));
                ls.add(rs.getString("address_2"));
                ls.add(rs.getString("town_city"));
                ls.add(rs.getString("county"));
                ls.add(rs.getString("postcode"));
                ls.add(rs.getString("country"));
                ls.add(rs.getString("customer_type"));
                ls.add(rs.getString("email"));
                ls.add(String.valueOf(rs.getLong("contact_no")));
                ls.add(rs.getString("type"));
                System.out.println("Opened customer account : " + String.valueOf(rs.getInt("customer_id")));
                new MySQLQueries(conn).logAdd(new CodeSet().DateTime(true)+": Opened customer account : " + String.valueOf(rs.getInt("customer_id")));
            }
        } catch (SQLException e) {
            System.out.println("Exception in opening customer profile : " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OCustomerAccount(conn, s, new JFrame(), new String()).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accsus;
    private javax.swing.JButton addTask;
    private javax.swing.JPanel addTaskPanel;
    private javax.swing.JLabel address;
    private javax.swing.border.BevelBorder bevelBorder1;
    private javax.swing.JLabel cno;
    private javax.swing.JLabel del;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel fName;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pay;
    private javax.swing.JLabel role;
    private javax.swing.JLabel suspend;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
