/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEndGUI;

import BackEndCode.Bootstrap;
import BackEndCode.CodeSet;
import BackEndCode.IDgen;
import BackEndCode.MySQLQueries;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Sai
 */
public class SDashboard extends javax.swing.JFrame {

    private static Connection conn = null;
    
    private static List<String> ls = new ArrayList<String>();;
    
    private IDgen idg;
    

    /**
     * Creates new form Login
     */
    public SDashboard(Connection conn, List<String> ls) {
        
        idg = new IDgen();
        this.conn = conn;
        this.ls = ls;
        Bootstrap template = new Bootstrap();
        Toolkit windowSize = Toolkit.getDefaultToolkit();
        //this.setAlwaysOnTop(true);
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        this.setSize((int) windowSize.getScreenSize().getWidth(), (int) windowSize.getScreenSize().getHeight());
        setStat();
        setProfile(ls);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new cambodia.raven.DateChooser();
        dateChooser2 = new cambodia.raven.DateChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel11 = new javax.swing.JPanel();
        from = new javax.swing.JTextField();
        ipr0 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        employeeLogin20 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        ipr = new javax.swing.JButton();
        employeeLogin8 = new javax.swing.JLabel();
        reports = new javax.swing.JComboBox<>();
        employeeLogin9 = new javax.swing.JLabel();
        employeeLogin10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        employeeLogin5 = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        alertCount = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        activeAcc = new javax.swing.JLabel();
        employeeLogin15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        employeeLogin4 = new javax.swing.JLabel();
        employeeLogin99 = new javax.swing.JLabel();
        suspendNo = new javax.swing.JLabel();
        employeeLogin18 = new javax.swing.JLabel();
        statValued = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tj = new javax.swing.JLabel();
        employeeLogin11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        employeeLogin2 = new javax.swing.JLabel();
        addTask = new javax.swing.JButton();
        employeeLogin12 = new javax.swing.JLabel();
        cj = new javax.swing.JLabel();
        employeeLogin13 = new javax.swing.JLabel();
        oj = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        employeeLogin1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        ssearch = new javax.swing.JTextField();
        employeeLogin21 = new javax.swing.JLabel();
        Submit6 = new javax.swing.JButton();
        Submit7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        employeeLogin22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        csearch = new javax.swing.JTextField();
        employeeLogin = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Submit1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        employeeLogin3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        dateChooser1.setBackground(new java.awt.Color(171, 172, 173));
        dateChooser1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dateChooser1.setForeground(new java.awt.Color(171, 172, 173));
        dateChooser1.setButton(ipr0);
        dateChooser1.setTextRefernce(from);

        dateChooser2.setButton(ipr);
        dateChooser2.setTextRefernce(to);

        jPopupMenu1.setForeground(new java.awt.Color(51, 51, 51));

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(171, 172, 173));
        jPanel11.setForeground(new java.awt.Color(60, 63, 65));

        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromuserActionPerformed(evt);
            }
        });

        ipr0.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ipr0.setText("...");
        ipr0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipr0ActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(59, 63, 66));
        jPanel12.setForeground(new java.awt.Color(59, 63, 66));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin20.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin20.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin20.setText("Reports");
        jPanel12.add(employeeLogin20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 510, 70));

        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touserActionPerformed(evt);
            }
        });

        ipr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ipr.setText("...");
        ipr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iprActionPerformed(evt);
            }
        });

        employeeLogin8.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin8.setFont(employeeLogin8.getFont().deriveFont(employeeLogin8.getFont().getStyle() | java.awt.Font.BOLD, employeeLogin8.getFont().getSize()+2));
        employeeLogin8.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin8.setText("Select Peirod");

        reports.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indivisual Performance Report", "Summery Performance Report" }));

        employeeLogin9.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin9.setFont(employeeLogin9.getFont().deriveFont(employeeLogin9.getFont().getStyle() | java.awt.Font.BOLD, employeeLogin9.getFont().getSize()+2));
        employeeLogin9.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin9.setText("From");

        employeeLogin10.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin10.setFont(employeeLogin10.getFont().deriveFont(employeeLogin10.getFont().getStyle() | java.awt.Font.BOLD, employeeLogin10.getFont().getSize()+2));
        employeeLogin10.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin10.setText("To");

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employeeLogin8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ipr0))
                                .addComponent(employeeLogin9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipr))
                            .addComponent(employeeLogin10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLogin8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeLogin9)
                    .addComponent(employeeLogin10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipr0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 540, 570, 270));

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(171, 172, 173));

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setForeground(new java.awt.Color(59, 63, 66));
        jPanel15.setToolTipText("");
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setBackground(new java.awt.Color(59, 63, 66));
        id.setFont(id.getFont().deriveFont(id.getFont().getStyle() | java.awt.Font.BOLD, id.getFont().getSize()+2));
        id.setForeground(new java.awt.Color(59, 63, 66));
        id.setText("223445256");
        jPanel15.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 30));

        jPanel16.setBackground(new java.awt.Color(59, 63, 66));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(59, 63, 66));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(171, 172, 173));
        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getStyle() | java.awt.Font.BOLD, jLabel20.getFont().getSize()+2));
        jLabel20.setForeground(new java.awt.Color(171, 172, 173));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ID");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));
        jPanel18.setForeground(new java.awt.Color(59, 63, 66));
        jPanel18.setToolTipText("");
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        role.setBackground(new java.awt.Color(59, 63, 66));
        role.setFont(role.getFont().deriveFont(role.getFont().getStyle() | java.awt.Font.BOLD, role.getFont().getSize()+2));
        role.setForeground(new java.awt.Color(59, 63, 66));
        role.setText("Office Manager");
        jPanel18.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 210, 30));

        jPanel19.setBackground(new java.awt.Color(59, 63, 66));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(171, 172, 173));
        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+2));
        jLabel5.setForeground(new java.awt.Color(171, 172, 173));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Role ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel19.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel20.setBackground(new java.awt.Color(153, 153, 153));
        jPanel20.setForeground(new java.awt.Color(59, 63, 66));
        jPanel20.setToolTipText("");
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(59, 63, 66));
        name.setFont(name.getFont().deriveFont(name.getFont().getStyle() | java.awt.Font.BOLD, name.getFont().getSize()+2));
        name.setForeground(new java.awt.Color(59, 63, 66));
        name.setText("Sam");
        jPanel20.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 190, 30));

        jPanel21.setBackground(new java.awt.Color(59, 63, 66));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(171, 172, 173));
        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getStyle() | java.awt.Font.BOLD, jLabel19.getFont().getSize()+2));
        jLabel19.setForeground(new java.awt.Color(171, 172, 173));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" Name");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel21.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel10.setBackground(new java.awt.Color(59, 63, 66));
        jPanel10.setForeground(new java.awt.Color(59, 63, 66));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin5.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin5.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin5.setText("   Your Profile");
        jPanel10.add(employeeLogin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 70));

        alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/alert.png"))); // NOI18N
        alert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alertMouseClicked(evt);
            }
        });
        jPanel10.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 70, 70));

        alertCount.setFont(alertCount.getFont().deriveFont(alertCount.getFont().getSize()+3f));
        alertCount.setForeground(new java.awt.Color(171, 172, 173));
        alertCount.setText("0");
        jPanel10.add(alertCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 70));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(exit.getFont().deriveFont(exit.getFont().getStyle() | java.awt.Font.BOLD));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(exit))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 210, -1, 260));

        jPanel7.setBackground(new java.awt.Color(171, 172, 173));

        activeAcc.setBackground(new java.awt.Color(187, 187, 187));
        activeAcc.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        activeAcc.setForeground(new java.awt.Color(59, 63, 66));
        activeAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activeAcc.setText("125");

        employeeLogin15.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin15.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin15.setText("Active Accounts");
        employeeLogin15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin15.setFocusCycleRoot(true);
        employeeLogin15.setName(""); // NOI18N

        jPanel8.setBackground(new java.awt.Color(59, 63, 66));
        jPanel8.setForeground(new java.awt.Color(59, 63, 66));

        employeeLogin4.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin4.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin4.setText("   Overall Account Report");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(employeeLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        employeeLogin99.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin99.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin99.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin99.setText("Suspended Accounts");
        employeeLogin99.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin99.setFocusCycleRoot(true);
        employeeLogin99.setName(""); // NOI18N

        suspendNo.setBackground(new java.awt.Color(187, 187, 187));
        suspendNo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        suspendNo.setForeground(new java.awt.Color(59, 63, 66));
        suspendNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suspendNo.setText("22");

        employeeLogin18.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin18.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin18.setText("Valued Accounts");
        employeeLogin18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin18.setFocusCycleRoot(true);
        employeeLogin18.setName(""); // NOI18N

        statValued.setBackground(new java.awt.Color(187, 187, 187));
        statValued.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        statValued.setForeground(new java.awt.Color(59, 63, 66));
        statValued.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statValued.setText("03");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeLogin15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activeAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeLogin99, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(suspendNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeLogin18, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(statValued, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suspendNo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statValued, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLogin15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLogin99, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLogin18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 680, 260));

        jPanel4.setBackground(new java.awt.Color(171, 172, 173));

        tj.setBackground(new java.awt.Color(187, 187, 187));
        tj.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        tj.setForeground(new java.awt.Color(59, 63, 66));
        tj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tj.setText("200");

        employeeLogin11.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin11.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin11.setText("Total Jobs");
        employeeLogin11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin11.setFocusCycleRoot(true);
        employeeLogin11.setName(""); // NOI18N

        jPanel5.setBackground(new java.awt.Color(59, 63, 66));
        jPanel5.setForeground(new java.awt.Color(59, 63, 66));

        employeeLogin2.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin2.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin2.setText("   Overall Job Report");

        addTask.setBackground(new java.awt.Color(171, 172, 173));
        addTask.setFont(addTask.getFont().deriveFont(addTask.getFont().getStyle() | java.awt.Font.BOLD, addTask.getFont().getSize()+4));
        addTask.setForeground(new java.awt.Color(171, 172, 173));
        addTask.setText("View all jobs");
        addTask.setToolTipText("");
        addTask.setBorderPainted(false);
        addTask.setContentAreaFilled(false);
        addTask.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(employeeLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(employeeLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        employeeLogin12.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin12.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin12.setText("Completed Jobs");
        employeeLogin12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin12.setFocusCycleRoot(true);
        employeeLogin12.setName(""); // NOI18N

        cj.setBackground(new java.awt.Color(187, 187, 187));
        cj.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        cj.setForeground(new java.awt.Color(59, 63, 66));
        cj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cj.setText("123");

        employeeLogin13.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin13.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin13.setText("On-Hold Jobs");
        employeeLogin13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin13.setFocusCycleRoot(true);
        employeeLogin13.setName(""); // NOI18N

        oj.setBackground(new java.awt.Color(187, 187, 187));
        oj.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        oj.setForeground(new java.awt.Color(59, 63, 66));
        oj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oj.setText("77");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tj, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(employeeLogin11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cj, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(employeeLogin12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeLogin13, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(oj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLogin11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLogin12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLogin13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 680, 260));

        copyright.setBackground(new java.awt.Color(171, 172, 173));
        copyright.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(171, 172, 173));
        copyright.setText("©  2018  CODEX");
        jPanel1.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 1060, 110, -1));

        jPanel3.setBackground(new java.awt.Color(59, 63, 66));
        jPanel3.setForeground(new java.awt.Color(59, 63, 66));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin1.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        employeeLogin1.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin1.setText("Dashboard");
        jPanel3.add(employeeLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2, 530, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        jPanel13.setBackground(new java.awt.Color(171, 172, 173));
        jPanel13.setForeground(new java.awt.Color(60, 63, 65));

        ssearch.setText("Enter Keyword");
        ssearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssearchuserActionPerformed(evt);
            }
        });

        employeeLogin21.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin21.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin21.setText("Search ");

        Submit6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit6.setText("Create");
        Submit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit6ActionPerformed(evt);
            }
        });

        Submit7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit7.setText("Search");
        Submit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit7ActionPerformed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(59, 63, 66));
        jPanel14.setForeground(new java.awt.Color(59, 63, 66));

        employeeLogin22.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin22.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin22.setText("Staff Accounts");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(employeeLogin22, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeLogin22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLogin21, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssearch, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(Submit6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(Submit7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(employeeLogin21)
                .addGap(26, 26, 26)
                .addComponent(ssearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Submit6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 600, 270));

        jPanel2.setBackground(new java.awt.Color(171, 172, 173));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        csearch.setText("Enter Keyword");
        csearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        employeeLogin.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin.setText("Search ");

        Submit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit.setText("Create");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Submit1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit1.setText("Search");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(59, 63, 66));
        jPanel6.setForeground(new java.awt.Color(59, 63, 66));

        employeeLogin3.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin3.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin3.setText("Customer Accounts");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(employeeLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csearch, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(Submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(employeeLogin)
                .addGap(26, 26, 26)
                .addComponent(csearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 600, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3840x2560-3020841-black-and-white_camera_olympus_technology.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1919, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        this.enable(false);
        new NewCAcc(conn,this,role.getText()).show();
    }//GEN-LAST:event_SubmitActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed
        this.enable(false);
        new CustomerSearchList(conn, csearch.getText(),this,role.getText()).show();
    }//GEN-LAST:event_Submit1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new MySQLQueries(conn).logAdd(new CodeSet().DateTime(true) + ": Staff Account ID: " + ls.get(0) + ": Logged Out");
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void ssearchuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssearchuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssearchuserActionPerformed

    private void Submit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit6ActionPerformed
        this.enable(false);
        new NewStaffAcc(conn, this, role.getText()).show();
    }//GEN-LAST:event_Submit6ActionPerformed

    private void Submit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit7ActionPerformed
        this.enable(false);
        new StaffSearchList(conn, ssearch.getText(), this, role.getText()).show();
    }//GEN-LAST:event_Submit7ActionPerformed

    private void alertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alertMouseClicked
        new Alert(conn,role.getText(),this).show();
    }//GEN-LAST:event_alertMouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        if(role.getText().equals("Office Manager")||role.getText().equals("Shift Manager")){
            updateAlert();
        }
    }//GEN-LAST:event_jPanel1MouseMoved

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskActionPerformed

        new JobList(conn,this).show();
        this.disable();
    }//GEN-LAST:event_addTaskActionPerformed

    private void fromuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromuserActionPerformed

    private void ipr0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipr0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipr0ActionPerformed

    private void touserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_touserActionPerformed

    private void iprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iprActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(reports.getSelectedIndex() == 0){
            new CodeSet().individualPerformance(conn, new CodeSet().convertStringToDataString(to.getText(),true), new CodeSet().convertStringToDataString(from.getText(),true));
        } else{
             new CodeSet().summeryPerformance(conn, new CodeSet().convertStringToDataString(to.getText(),true), new CodeSet().convertStringToDataString(from.getText(),true));
        } 
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void setProfile(List<String> l){
        id.setText(idg.generate(Integer.parseInt(l.get(0)), 1));
        //id.setText(l.get(0));
        role.setText(l.get(1));
        if(role.getText().equals("Technician")){
                    role.setText(role.getText() + ", "+l.get(2));
                }
        name.setText(l.get(3)+" "+l.get(4));
        if(role.getText().equals("Office Manager")||role.getText().equals("Shift Manager")){
            alert.setVisible(true);
            alertCount.setVisible(true);
            updateAlert();
        } else {
            alert.setVisible(false);
            alertCount.setVisible(false);
        }
        
        new MySQLQueries(conn).deadline();
    }
    
    public void updateAlert(){
        alertCount.setText(String.valueOf(new MySQLQueries(conn).notification(role.getText()).getRowCount()));
    }
    
    public void setStat(){
        statValued.setText(new MySQLQueries(conn).getValuedCAccNo());
        suspendNo.setText(new MySQLQueries(conn).getsuspendedCAccNo(true));
        activeAcc.setText(new MySQLQueries(conn).getsuspendedCAccNo(false));
        tj.setText(new MySQLQueries(conn).Jobs(1));
        cj.setText(new MySQLQueries(conn).Jobs(2));
        oj.setText(new MySQLQueries(conn).Jobs(3));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDashboard(conn,ls).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton Submit1;
    private javax.swing.JButton Submit6;
    private javax.swing.JButton Submit7;
    private javax.swing.JLabel activeAcc;
    private javax.swing.JButton addTask;
    private javax.swing.JLabel alert;
    private javax.swing.JLabel alertCount;
    private javax.swing.JLabel cj;
    private javax.swing.JLabel copyright;
    private javax.swing.JTextField csearch;
    private cambodia.raven.DateChooser dateChooser1;
    private cambodia.raven.DateChooser dateChooser2;
    private javax.swing.JLabel employeeLogin;
    private javax.swing.JLabel employeeLogin1;
    private javax.swing.JLabel employeeLogin10;
    private javax.swing.JLabel employeeLogin11;
    private javax.swing.JLabel employeeLogin12;
    private javax.swing.JLabel employeeLogin13;
    private javax.swing.JLabel employeeLogin15;
    private javax.swing.JLabel employeeLogin18;
    private javax.swing.JLabel employeeLogin2;
    private javax.swing.JLabel employeeLogin20;
    private javax.swing.JLabel employeeLogin21;
    private javax.swing.JLabel employeeLogin22;
    private javax.swing.JLabel employeeLogin3;
    private javax.swing.JLabel employeeLogin4;
    private javax.swing.JLabel employeeLogin5;
    private javax.swing.JLabel employeeLogin8;
    private javax.swing.JLabel employeeLogin9;
    private javax.swing.JLabel employeeLogin99;
    private javax.swing.JButton exit;
    private javax.swing.JTextField from;
    private javax.swing.JLabel id;
    private javax.swing.JButton ipr;
    private javax.swing.JButton ipr0;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel oj;
    private javax.swing.JComboBox<String> reports;
    private javax.swing.JLabel role;
    private javax.swing.JTextField ssearch;
    private javax.swing.JLabel statValued;
    private javax.swing.JLabel suspendNo;
    private javax.swing.JLabel tj;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
