/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEndGUI;

import BackEndCode.Bootstrap;
import BackEndCode.CodeSet;
import BackEndCode.IDgen;
import BackEndCode.MySQLQueries;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Sai
 */
public class TDashboard extends javax.swing.JFrame {

    private static Connection conn = null;

    private static List<String> ls, l;

    private String s;

    private IDgen idg;

    /**
     * Creates new form Login
     */
    public TDashboard(Connection conn, List<String> ls) {

        idg = new IDgen();
        this.conn = conn;
        this.ls = ls;
        this.s = new String();
        Bootstrap template = new Bootstrap();
        Toolkit windowSize = Toolkit.getDefaultToolkit();
        //this.setAlwaysOnTop(true);
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        this.setSize((int) windowSize.getScreenSize().getWidth(), (int) windowSize.getScreenSize().getHeight());
        setProfile(ls);
        si.setText("<HTML>There is no task for you or No task is assigned to you. Please contact Shift Manager or Office Manager </HTML>");
        assignToStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new cambodia.raven.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        employeeLogin20 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        cid = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        si = new javax.swing.JLabel();
        jtid = new javax.swing.JLabel();
        jid = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        employeeLogin26 = new javax.swing.JLabel();
        employeeLogin27 = new javax.swing.JLabel();
        employeeLogin15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        employeeLogin17 = new javax.swing.JLabel();
        employeeLogin19 = new javax.swing.JLabel();
        employeeLogin22 = new javax.swing.JLabel();
        task = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        employeeLogin5 = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        alertCount = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tj = new javax.swing.JLabel();
        employeeLogin11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        employeeLogin2 = new javax.swing.JLabel();
        addTask = new javax.swing.JButton();
        xdscd = new javax.swing.JLabel();
        cj = new javax.swing.JLabel();
        dcdcd = new javax.swing.JLabel();
        oj = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        employeeLogin1 = new javax.swing.JLabel();
        log = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        dateChooser1.setBackground(new java.awt.Color(171, 172, 173));
        dateChooser1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dateChooser1.setForeground(new java.awt.Color(171, 172, 173));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(171, 172, 173));
        jPanel11.setForeground(new java.awt.Color(60, 63, 65));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(59, 63, 66));
        jPanel12.setForeground(new java.awt.Color(59, 63, 66));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin20.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin20.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin20.setText("Work Details");
        jPanel12.add(employeeLogin20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 180, 70));

        update.setBackground(new java.awt.Color(171, 172, 173));
        update.setForeground(new java.awt.Color(59, 63, 66));
        update.setText("Update Status");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel12.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, 40));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        cid.setBackground(new java.awt.Color(187, 187, 187));
        cid.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        cid.setForeground(new java.awt.Color(59, 63, 66));
        cid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cid.setText("000000");
        cid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cid.setFocusCycleRoot(true);
        cid.setName(""); // NOI18N
        jPanel11.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 390, 110));

        date.setBackground(new java.awt.Color(187, 187, 187));
        date.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        date.setForeground(new java.awt.Color(59, 63, 66));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("0000-00-00");
        date.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        date.setFocusCycleRoot(true);
        date.setName(""); // NOI18N
        jPanel11.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 360, 110));

        si.setBackground(new java.awt.Color(187, 187, 187));
        si.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        si.setForeground(new java.awt.Color(59, 63, 66));
        si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        si.setText("sdfsdfsdf");
        si.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        si.setFocusCycleRoot(true);
        si.setName(""); // NOI18N
        jPanel11.add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 340, 120));

        jtid.setBackground(new java.awt.Color(187, 187, 187));
        jtid.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jtid.setForeground(new java.awt.Color(59, 63, 66));
        jtid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtid.setText("0");
        jtid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtid.setFocusCycleRoot(true);
        jtid.setName(""); // NOI18N
        jPanel11.add(jtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 110));

        jid.setBackground(new java.awt.Color(187, 187, 187));
        jid.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jid.setForeground(new java.awt.Color(59, 63, 66));
        jid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jid.setText("00000000000000");
        jid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jid.setFocusCycleRoot(true);
        jid.setName(""); // NOI18N
        jPanel11.add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 350, 110));

        jPanel6.setBackground(new java.awt.Color(59, 63, 66));
        jPanel6.setForeground(new java.awt.Color(59, 63, 66));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin26.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin26.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin26.setText("Task");
        employeeLogin26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin26.setFocusCycleRoot(true);
        employeeLogin26.setName(""); // NOI18N
        jPanel6.add(employeeLogin26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 350, 50));

        employeeLogin27.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin27.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin27.setText("Special Instruction");
        employeeLogin27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin27.setFocusCycleRoot(true);
        employeeLogin27.setName(""); // NOI18N
        jPanel6.add(employeeLogin27, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 360, 50));

        employeeLogin15.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin15.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin15.setText("Customer ID");
        employeeLogin15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin15.setFocusCycleRoot(true);
        employeeLogin15.setName(""); // NOI18N
        jPanel6.add(employeeLogin15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));

        jPanel11.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1100, 50));

        jPanel2.setBackground(new java.awt.Color(59, 63, 66));
        jPanel2.setForeground(new java.awt.Color(59, 63, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin17.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin17.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin17.setText("Job ID");
        employeeLogin17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin17.setFocusCycleRoot(true);
        employeeLogin17.setName(""); // NOI18N
        jPanel2.add(employeeLogin17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 350, 50));

        employeeLogin19.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin19.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin19.setText("Deadline");
        employeeLogin19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin19.setFocusCycleRoot(true);
        employeeLogin19.setName(""); // NOI18N
        jPanel2.add(employeeLogin19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 360, 50));

        employeeLogin22.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin22.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin22.setText("Jod-Task ID");
        employeeLogin22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin22.setFocusCycleRoot(true);
        employeeLogin22.setName(""); // NOI18N
        jPanel2.add(employeeLogin22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));

        jPanel11.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1100, 50));

        task.setBackground(new java.awt.Color(187, 187, 187));
        task.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        task.setForeground(new java.awt.Color(59, 63, 66));
        task.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        task.setText("Null");
        task.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        task.setFocusCycleRoot(true);
        task.setName(""); // NOI18N
        jPanel11.add(task, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 350, 120));

        jPanel7.setBackground(new java.awt.Color(59, 63, 66));
        jPanel7.setForeground(new java.awt.Color(59, 63, 66));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 2, 310));

        jPanel8.setBackground(new java.awt.Color(59, 63, 66));
        jPanel8.setForeground(new java.awt.Color(59, 63, 66));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 2, 310));

        jPanel13.setBackground(new java.awt.Color(59, 63, 66));
        jPanel13.setForeground(new java.awt.Color(59, 63, 66));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 3, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 1100, 430));

        jPanel9.setBackground(new java.awt.Color(171, 172, 173));

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setForeground(new java.awt.Color(59, 63, 66));
        jPanel15.setToolTipText("");
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setBackground(new java.awt.Color(59, 63, 66));
        id.setFont(id.getFont().deriveFont(id.getFont().getStyle() | java.awt.Font.BOLD, id.getFont().getSize()+2));
        id.setForeground(new java.awt.Color(59, 63, 66));
        id.setText("223445256");
        jPanel15.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 30));

        jPanel16.setBackground(new java.awt.Color(59, 63, 66));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(59, 63, 66));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(171, 172, 173));
        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getStyle() | java.awt.Font.BOLD, jLabel20.getFont().getSize()+2));
        jLabel20.setForeground(new java.awt.Color(171, 172, 173));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ID");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));
        jPanel18.setForeground(new java.awt.Color(59, 63, 66));
        jPanel18.setToolTipText("");
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        role.setBackground(new java.awt.Color(59, 63, 66));
        role.setFont(role.getFont().deriveFont(role.getFont().getStyle() | java.awt.Font.BOLD, role.getFont().getSize()+2));
        role.setForeground(new java.awt.Color(59, 63, 66));
        role.setText("Office Manager");
        jPanel18.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 250, 30));

        jPanel19.setBackground(new java.awt.Color(59, 63, 66));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(171, 172, 173));
        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+2));
        jLabel5.setForeground(new java.awt.Color(171, 172, 173));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Role ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel19.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel20.setBackground(new java.awt.Color(153, 153, 153));
        jPanel20.setForeground(new java.awt.Color(59, 63, 66));
        jPanel20.setToolTipText("");
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(59, 63, 66));
        name.setFont(name.getFont().deriveFont(name.getFont().getStyle() | java.awt.Font.BOLD, name.getFont().getSize()+2));
        name.setForeground(new java.awt.Color(59, 63, 66));
        name.setText("Sam");
        jPanel20.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 190, 30));

        jPanel21.setBackground(new java.awt.Color(59, 63, 66));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(171, 172, 173));
        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getStyle() | java.awt.Font.BOLD, jLabel19.getFont().getSize()+2));
        jLabel19.setForeground(new java.awt.Color(171, 172, 173));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" Name");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel21.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel10.setBackground(new java.awt.Color(59, 63, 66));
        jPanel10.setForeground(new java.awt.Color(59, 63, 66));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin5.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin5.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin5.setText("   Your Profile");
        jPanel10.add(employeeLogin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 70));

        alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/alert.png"))); // NOI18N
        alert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alertMouseClicked(evt);
            }
        });
        jPanel10.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 70, 70));

        alertCount.setFont(alertCount.getFont().deriveFont(alertCount.getFont().getSize()+3f));
        alertCount.setForeground(new java.awt.Color(171, 172, 173));
        alertCount.setText("0");
        jPanel10.add(alertCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 70));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(exit.getFont().deriveFont(exit.getFont().getStyle() | java.awt.Font.BOLD));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(exit))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 210, -1, 260));

        jPanel4.setBackground(new java.awt.Color(171, 172, 173));

        tj.setBackground(new java.awt.Color(187, 187, 187));
        tj.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        tj.setForeground(new java.awt.Color(59, 63, 66));
        tj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tj.setText("200");

        employeeLogin11.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin11.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin11.setText("Total Jobs");
        employeeLogin11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin11.setFocusCycleRoot(true);
        employeeLogin11.setName(""); // NOI18N

        jPanel5.setBackground(new java.awt.Color(59, 63, 66));
        jPanel5.setForeground(new java.awt.Color(59, 63, 66));

        employeeLogin2.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin2.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin2.setText("   Overall Job Report");

        addTask.setBackground(new java.awt.Color(171, 172, 173));
        addTask.setFont(addTask.getFont().deriveFont(addTask.getFont().getStyle() | java.awt.Font.BOLD, addTask.getFont().getSize()+4));
        addTask.setForeground(new java.awt.Color(171, 172, 173));
        addTask.setText("View all jobs");
        addTask.setToolTipText("");
        addTask.setBorderPainted(false);
        addTask.setContentAreaFilled(false);
        addTask.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(employeeLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(employeeLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        xdscd.setBackground(new java.awt.Color(187, 187, 187));
        xdscd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        xdscd.setForeground(new java.awt.Color(59, 63, 66));
        xdscd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xdscd.setText("Completed Jobs");
        xdscd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        xdscd.setFocusCycleRoot(true);
        xdscd.setName(""); // NOI18N

        cj.setBackground(new java.awt.Color(187, 187, 187));
        cj.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        cj.setForeground(new java.awt.Color(59, 63, 66));
        cj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cj.setText("123");

        dcdcd.setBackground(new java.awt.Color(187, 187, 187));
        dcdcd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dcdcd.setForeground(new java.awt.Color(59, 63, 66));
        dcdcd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dcdcd.setText("On-Hold Jobs");
        dcdcd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dcdcd.setFocusCycleRoot(true);
        dcdcd.setName(""); // NOI18N

        oj.setBackground(new java.awt.Color(187, 187, 187));
        oj.setFont(new java.awt.Font("Microsoft JhengHei", 1, 90)); // NOI18N
        oj.setForeground(new java.awt.Color(59, 63, 66));
        oj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oj.setText("77");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tj, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(employeeLogin11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cj, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(xdscd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcdcd, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(oj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLogin11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xdscd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcdcd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 680, 260));

        copyright.setBackground(new java.awt.Color(171, 172, 173));
        copyright.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(171, 172, 173));
        copyright.setText("©  2018  CODEX");
        jPanel1.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 1060, 110, -1));

        jPanel3.setBackground(new java.awt.Color(59, 63, 66));
        jPanel3.setForeground(new java.awt.Color(59, 63, 66));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin1.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        employeeLogin1.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin1.setText("Dashboard");
        jPanel3.add(employeeLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2, 530, 70));

        log.setBackground(new java.awt.Color(171, 172, 173));
        log.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        log.setText("View Logs");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel3.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3840x2560-3020841-black-and-white_camera_olympus_technology.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1919, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new MySQLQueries(conn).logAdd(new CodeSet().DateTime(true) + ": Staff Account ID: " + ls.get(0) + ": Logged Out");
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void alertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alertMouseClicked
        new Alert(conn, role.getText(), this).show();
    }//GEN-LAST:event_alertMouseClicked

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        new Logger(conn, this).show();
        this.enable(false);
    }//GEN-LAST:event_logActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        if (role.getText().equals("Office Manager") || role.getText().equals("Shift Manager")) {
            updateAlert();
        }
    }//GEN-LAST:event_jPanel1MouseMoved

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskActionPerformed

        new JobList(conn, this).show();
        this.disable();
    }//GEN-LAST:event_addTaskActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        new UpdateTask(conn, s, l.get(0), this).show();
        this.disable();
    }//GEN-LAST:event_updateActionPerformed

    private void setProfile(List<String> l) {
        s = (l.get(0));
        id.setText(idg.generate(Integer.parseInt(l.get(0)), 1));
        role.setText(l.get(1));
        if (role.getText().equals("Technician")) {
            role.setText(role.getText() + ", " + l.get(2));
        }
        name.setText(l.get(3) + " " + l.get(4));
        if (role.getText().equals("Office Manager") || role.getText().equals("Shift Manager")) {
            alert.setVisible(true);
            alertCount.setVisible(true);
            updateAlert();
        } else {
            alert.setVisible(false);
            alertCount.setVisible(false);
        }
        if (l.get(1).equals("Office Manager")) {
            log.setVisible(true);
        } else {
            log.setVisible(false);
        }
        new MySQLQueries(conn).deadline();
    }

    public void updateAlert() {
        alertCount.setText(String.valueOf(new MySQLQueries(conn).notification(role.getText()).getRowCount()));
    }

    public void setStat() {

        tj.setText(new MySQLQueries(conn).Jobs(1));
        cj.setText(new MySQLQueries(conn).Jobs(2));
        oj.setText(new MySQLQueries(conn).Jobs(3));
        l = new MySQLQueries(conn).techPopulate(ls.get(0));
        if (!(l == null)) {
            jtid.setText(l.get(0));
            jid.setText(l.get(1));
            date.setText(l.get(2));
            cid.setText(new IDgen().generate(Integer.parseInt(l.get(3)), 2));
            task.setText(l.get(4));
            si.setText("<HTML>" + l.get(5) + "</HTML>");
        } else {
            update.setVisible(false);
        }
    }

    public void assignToStaff() {

        if (new MySQLQueries(conn).checkStaff(ls.get(0))) {
            setStat();
        } else {
            new MySQLQueries(conn).assignToStaff(ls.get(0), ls.get(2));
            setStat();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TDashboard(conn, ls).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTask;
    private javax.swing.JLabel alert;
    private javax.swing.JLabel alertCount;
    private javax.swing.JLabel cid;
    private javax.swing.JLabel cj;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel date;
    private cambodia.raven.DateChooser dateChooser1;
    private javax.swing.JLabel dcdcd;
    private javax.swing.JLabel employeeLogin1;
    private javax.swing.JLabel employeeLogin11;
    private javax.swing.JLabel employeeLogin15;
    private javax.swing.JLabel employeeLogin17;
    private javax.swing.JLabel employeeLogin19;
    private javax.swing.JLabel employeeLogin2;
    private javax.swing.JLabel employeeLogin20;
    private javax.swing.JLabel employeeLogin22;
    private javax.swing.JLabel employeeLogin26;
    private javax.swing.JLabel employeeLogin27;
    private javax.swing.JLabel employeeLogin5;
    private javax.swing.JButton exit;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jtid;
    private javax.swing.JButton log;
    private javax.swing.JLabel name;
    private javax.swing.JLabel oj;
    private javax.swing.JLabel role;
    private javax.swing.JLabel si;
    private javax.swing.JLabel task;
    private javax.swing.JLabel tj;
    private javax.swing.JButton update;
    private javax.swing.JLabel xdscd;
    // End of variables declaration//GEN-END:variables
}
