/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPanels;

import codex.*;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Sai
 */
public class Dashboard extends javax.swing.JFrame {

    private static Connection conn = null;

    private PreparedStatement pst = null;

    private ResultSet rs = null;

    /**
     * Creates new form Login
     */
    public Dashboard(Connection conn) {
        this.conn = conn;
        Bootstrap template = new Bootstrap();
        Toolkit windowSize = Toolkit.getDefaultToolkit();
        //this.setAlwaysOnTop(true);
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        this.setSize((int) windowSize.getScreenSize().getWidth(), (int) windowSize.getScreenSize().getHeight());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        username4 = new javax.swing.JTextField();
        employeeLogin7 = new javax.swing.JLabel();
        Submit4 = new javax.swing.JButton();
        username5 = new javax.swing.JTextField();
        Submit5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        employeeLogin20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        employeeLogin14 = new javax.swing.JLabel();
        employeeLogin15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        employeeLogin4 = new javax.swing.JLabel();
        employeeLogin16 = new javax.swing.JLabel();
        employeeLogin17 = new javax.swing.JLabel();
        employeeLogin18 = new javax.swing.JLabel();
        employeeLogin19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        employeeLogin8 = new javax.swing.JLabel();
        employeeLogin11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        employeeLogin2 = new javax.swing.JLabel();
        employeeLogin12 = new javax.swing.JLabel();
        employeeLogin9 = new javax.swing.JLabel();
        employeeLogin13 = new javax.swing.JLabel();
        employeeLogin10 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        employeeLogin1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        ssearch = new javax.swing.JTextField();
        employeeLogin21 = new javax.swing.JLabel();
        Submit6 = new javax.swing.JButton();
        Submit7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        employeeLogin22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        csearch = new javax.swing.JTextField();
        employeeLogin = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Submit1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        employeeLogin3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(171, 172, 173));
        jPanel11.setForeground(new java.awt.Color(60, 63, 65));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username4.setText("Customer's Email");
        username4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username4userActionPerformed(evt);
            }
        });
        jPanel11.add(username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 460, 43));

        employeeLogin7.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin7.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin7.setText("Search ");
        jPanel11.add(employeeLogin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 350, -1));

        Submit4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit4.setText("Create");
        Submit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit4ActionPerformed(evt);
            }
        });
        jPanel11.add(Submit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 40));

        username5.setText("Customer's Name");
        username5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username5userActionPerformed(evt);
            }
        });
        jPanel11.add(username5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 460, 43));

        Submit5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit5.setText("Search");
        Submit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit5ActionPerformed(evt);
            }
        });
        jPanel11.add(Submit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, 40));

        jPanel12.setBackground(new java.awt.Color(59, 63, 66));
        jPanel12.setForeground(new java.awt.Color(59, 63, 66));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin20.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin20.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin20.setText("Customers");
        jPanel12.add(employeeLogin20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 530, 70));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 600, 340));

        jPanel7.setBackground(new java.awt.Color(171, 172, 173));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin14.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 100)); // NOI18N
        employeeLogin14.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin14.setText("125");
        jPanel7.add(employeeLogin14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 90));

        employeeLogin15.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin15.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin15.setText("Active Accounts");
        employeeLogin15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin15.setFocusCycleRoot(true);
        employeeLogin15.setName(""); // NOI18N
        jPanel7.add(employeeLogin15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));

        jPanel8.setBackground(new java.awt.Color(59, 63, 66));
        jPanel8.setForeground(new java.awt.Color(59, 63, 66));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin4.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin4.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin4.setText("   Overall Account Report");
        jPanel8.add(employeeLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        employeeLogin16.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin16.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin16.setText("Suspended Accounts");
        employeeLogin16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin16.setFocusCycleRoot(true);
        employeeLogin16.setName(""); // NOI18N
        jPanel7.add(employeeLogin16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 200, 30));

        employeeLogin17.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin17.setFont(new java.awt.Font("Microsoft JhengHei", 1, 100)); // NOI18N
        employeeLogin17.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin17.setText("22");
        jPanel7.add(employeeLogin17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 180, 90));

        employeeLogin18.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin18.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin18.setText("Default Accounts");
        employeeLogin18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin18.setFocusCycleRoot(true);
        employeeLogin18.setName(""); // NOI18N
        jPanel7.add(employeeLogin18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 180, 30));

        employeeLogin19.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin19.setFont(new java.awt.Font("Microsoft JhengHei", 1, 100)); // NOI18N
        employeeLogin19.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin19.setText("03");
        jPanel7.add(employeeLogin19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 180, 90));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 210, 680, 260));

        jPanel4.setBackground(new java.awt.Color(171, 172, 173));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin8.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 100)); // NOI18N
        employeeLogin8.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin8.setText("200");
        jPanel4.add(employeeLogin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 90));

        employeeLogin11.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin11.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin11.setText("Total Jobs");
        employeeLogin11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin11.setFocusCycleRoot(true);
        employeeLogin11.setName(""); // NOI18N
        jPanel4.add(employeeLogin11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));

        jPanel5.setBackground(new java.awt.Color(59, 63, 66));
        jPanel5.setForeground(new java.awt.Color(59, 63, 66));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin2.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin2.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin2.setText("   Overall Job Report");
        jPanel5.add(employeeLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        employeeLogin12.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin12.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin12.setText("Completed Jobs");
        employeeLogin12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin12.setFocusCycleRoot(true);
        employeeLogin12.setName(""); // NOI18N
        jPanel4.add(employeeLogin12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 180, 30));

        employeeLogin9.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 100)); // NOI18N
        employeeLogin9.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin9.setText("123");
        jPanel4.add(employeeLogin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 180, 90));

        employeeLogin13.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin13.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin13.setText("In-Complete Jobs");
        employeeLogin13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeLogin13.setFocusCycleRoot(true);
        employeeLogin13.setName(""); // NOI18N
        jPanel4.add(employeeLogin13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 180, 30));

        employeeLogin10.setBackground(new java.awt.Color(187, 187, 187));
        employeeLogin10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 100)); // NOI18N
        employeeLogin10.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLogin10.setText("77");
        jPanel4.add(employeeLogin10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 180, 90));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 680, 260));

        copyright.setBackground(new java.awt.Color(171, 172, 173));
        copyright.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(171, 172, 173));
        copyright.setText("©  2018  CODEX");
        jPanel1.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 1060, 110, -1));

        jPanel3.setBackground(new java.awt.Color(59, 63, 66));
        jPanel3.setForeground(new java.awt.Color(59, 63, 66));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin1.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin1.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin1.setText("Dashboard");
        jPanel3.add(employeeLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2, 530, 70));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, -10, 90, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, -1));

        jPanel13.setBackground(new java.awt.Color(171, 172, 173));
        jPanel13.setForeground(new java.awt.Color(60, 63, 65));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ssearch.setText("Enter Keyword");
        ssearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssearchuserActionPerformed(evt);
            }
        });
        jPanel13.add(ssearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 460, 43));

        employeeLogin21.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin21.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin21.setText("Search ");
        jPanel13.add(employeeLogin21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 350, -1));

        Submit6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit6.setText("Create");
        Submit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit6ActionPerformed(evt);
            }
        });
        jPanel13.add(Submit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, 40));

        Submit7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit7.setText("Search");
        Submit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit7ActionPerformed(evt);
            }
        });
        jPanel13.add(Submit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 40));

        jPanel14.setBackground(new java.awt.Color(59, 63, 66));
        jPanel14.setForeground(new java.awt.Color(59, 63, 66));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin22.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin22.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin22.setText("Staff Accounts");
        jPanel14.add(employeeLogin22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 530, 70));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 600, 270));

        jPanel2.setBackground(new java.awt.Color(171, 172, 173));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        csearch.setText("Enter Keyword");
        csearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel2.add(csearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 460, 43));

        employeeLogin.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        employeeLogin.setForeground(new java.awt.Color(59, 63, 66));
        employeeLogin.setText("Search ");
        jPanel2.add(employeeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 350, -1));

        Submit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit.setText("Create");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel2.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, 40));

        Submit1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Submit1.setText("Search");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });
        jPanel2.add(Submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 40));

        jPanel6.setBackground(new java.awt.Color(59, 63, 66));
        jPanel6.setForeground(new java.awt.Color(59, 63, 66));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLogin3.setBackground(new java.awt.Color(171, 172, 173));
        employeeLogin3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        employeeLogin3.setForeground(new java.awt.Color(171, 172, 173));
        employeeLogin3.setText("Customer Accounts");
        jPanel6.add(employeeLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 530, 70));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 560, 600, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3840x2560-3020841-black-and-white_camera_olympus_technology.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -1, 2050, 1260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1919, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        new NewCAcc(conn).show();
    }//GEN-LAST:event_SubmitActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed
        // TODO add your handling code here:
        new CustomerSearchList(conn, csearch.getText()).show();
    }//GEN-LAST:event_Submit1ActionPerformed

    private void username4userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username4userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username4userActionPerformed

    private void Submit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Submit4ActionPerformed

    private void username5userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username5userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username5userActionPerformed

    private void Submit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Submit5ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void ssearchuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssearchuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssearchuserActionPerformed

    private void Submit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit6ActionPerformed
        // TODO add your handling code here:
        new NewStaffAcc().show();
    }//GEN-LAST:event_Submit6ActionPerformed

    private void Submit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit7ActionPerformed
        // TODO add your handling code here:
        new StaffSearchList(conn, ssearch.getText()).show();
    }//GEN-LAST:event_Submit7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton Submit1;
    private javax.swing.JButton Submit4;
    private javax.swing.JButton Submit5;
    private javax.swing.JButton Submit6;
    private javax.swing.JButton Submit7;
    private javax.swing.JLabel copyright;
    private javax.swing.JTextField csearch;
    private javax.swing.JLabel employeeLogin;
    private javax.swing.JLabel employeeLogin1;
    private javax.swing.JLabel employeeLogin10;
    private javax.swing.JLabel employeeLogin11;
    private javax.swing.JLabel employeeLogin12;
    private javax.swing.JLabel employeeLogin13;
    private javax.swing.JLabel employeeLogin14;
    private javax.swing.JLabel employeeLogin15;
    private javax.swing.JLabel employeeLogin16;
    private javax.swing.JLabel employeeLogin17;
    private javax.swing.JLabel employeeLogin18;
    private javax.swing.JLabel employeeLogin19;
    private javax.swing.JLabel employeeLogin2;
    private javax.swing.JLabel employeeLogin20;
    private javax.swing.JLabel employeeLogin21;
    private javax.swing.JLabel employeeLogin22;
    private javax.swing.JLabel employeeLogin3;
    private javax.swing.JLabel employeeLogin4;
    private javax.swing.JLabel employeeLogin7;
    private javax.swing.JLabel employeeLogin8;
    private javax.swing.JLabel employeeLogin9;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField ssearch;
    private javax.swing.JTextField username4;
    private javax.swing.JTextField username5;
    // End of variables declaration//GEN-END:variables
}
